### ISSUE TITLE
CAS Support

### ISSUE THREAD

**Issue by sgrunt91** [exo-docker/exo-community#1]
Hi,

How could I configure CAS server with the docker container ? 

I've added `-e EXO_ADDONS_LIST="exo-cas"` at container creation, but for the configuration I don't know how to do that...

I'm thinking of this part: https://www.exoplatform.com/docs/PLF43/eXoAddonsGuide.SSO.CAS.eXoPlatform_server_configuration.html

Any help ? 

Regards,
Sgrunt

**Comment by jerrac** [comment]
Wow this is an old issue. 

If anyone is looking at this, I'd guess you would use a bind mount to mount the .properties config file wherever it's supposed to go.

I've actually asked about this here: https://community.exoplatform.com/portal/g/:spaces:docker/docker/forum/topic/topic38a8d9bd9e453452228ff6704d5df304 as well.

**Comment by fdrouet** [comment]
Hello @jerrac ,

I just gave the response in https://community.exoplatform.com/portal/g/:spaces:docker/docker/forum/topic/topic38a8d9bd9e4
53452228ff6704d5df304 .

Regards
Fred
