### ISSUE TITLE
Problem with font on signup step

### ISSUE THREAD

**Issue by artemkamolodets** [exo-docker/exo-community#7]
Hello.
I just deployed exo-community (docker) and have problem on signup stage: there is question marks instead of characters.
![exo_font](https://user-images.githubusercontent.com/30933691/46424546-1f32ec00-c742-11e8-933f-736b142e43b4.jpg)

How can i resolve this issue?
Here is compose file:

---
version: '2'
services:
  exo:
    image: exoplatform/exo-community
    environment:
      EXO_PROXY_VHOST: exo.somedomain.org
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: exo-mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: exo12345
      EXO_DB_TIMEOUT: 60
      EXO_JVM_LOG_GC_ENABLED: "true"
      EXO_MAIL_FROM: exo@somedomain.org
      EXO_MAIL_SMTP_HOST: somehost
      EXO_MAIL_SMTP_PORT: 25
      EXO_MONGO_HOST: exo-mongo
      EXO_ADDONS_LIST: exo-chat:$${CHAT_VERSION}
      EXO_JVM_USER_LANGUAGE: en
      EXO_JVM_USER_REGION: US
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    depends_on:
      - exo-mysql
      - exo-mongo
  exo-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: exo12345
    volumes:
      - mysql_data:/var/lib/mysql
  exo-mongo:
    image: mongo:3.4
    volumes:
      - mongo_data:/data/db:rw

volumes:
  exo_data:
  exo_logs:
  mysql_data:
  mongo_data:`

**Comment by fdrouet** [comment]
Please use eXo Tribe website forum to report problem : https://community.exoplatform.com/portal/intranet/forum
